train_data_path: "./datasets/cnews.train.txt"
val_data_path: "./datasets/cnews.val.txt"
test_data_path: "./datasets/cnews.test.txt"
model_path: "./model/logistic_model.pkl"
vectorizer_path: "./model/vectorizer.pkl"
ngram: 1
max_features: 5000
learning_rate: 0.01
epochs: 10
batch_size: 32
